name: Run Test

on:
  push:
    branches: [ master, main ]

jobs:
  test:
    name: Node.js Test
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1
      with:
        node-version: 12.18.0

    - name: npm install
      run: npm install

    - name: Run mocha
      run: ./node_modules/.bin/mocha